### ISSUE TITLE
보안의 에러 치명적인.

### ISSUE THREAD

**Issue by JeongTaehwan** [KyungJunNoh/Nodejs_Study#1]
안녕 ~! 당신은 에러가있어보인다. 코드에 당신은 보안때문에 Database connecting 옵션을  알고있다. 나누어놓은걸로 배태현군의 조언을받아.
하지만 깃허브를 코드를 보았다. 돌아보다가 나는   "gitignore"가 안되어있는것을 당신의 db.json이 so 치명적인 보안이슈가 있을수있다. 이것을 확인한다면 당신은 고쳐주길 바란다. 최대한 빨리 당신의 Database가 털리기 싫다면.  당신은 한때 전공이 보안이였던 사람이 맞나? 안녕.

**Comment by JeongTaehwan** [comment]
확인을 하고 gitignore를 하더라도 지금 가려지지 않을것이다 so 다시올리길 바란다. 삭제하고,

**Comment by qoxogus** [comment]
**oh... good issue!!**
